// Generated by CoffeeScript 1.9.3
var Board;

Board = (function() {
  function Board() {
    this.max = 2;
    this.size = {
      cols: 8,
      rows: 8
    };
    this.rows = [];
    this.add_row();
  }

  Board.prototype.add_row = function() {
    var row;
    row = new Row(this.size.cols, this.max);
    return this.rows.unshift(row);
  };

  return Board;

})();
