// Generated by CoffeeScript 1.9.3
var Board;

Board = (function() {
  function Board() {
    this.max = 2;
    this.size = {
      cols: 8,
      rows: 8
    };
    this.cols = this.empty_board();
  }

  Board.prototype.empty_board = function() {
    var cols, i, j, ref;
    cols = [];
    for (i = j = 0, ref = this.size.cols - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      cols.push([]);
    }
    return cols;
  };

  Board.prototype.add_pieces = function() {
    var col, j, len, ref, results;
    ref = this.cols;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      col = ref[j];
      if (Math.random() > 0.5) {
        results.push(col.unshift(new Piece(this.max)));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  return Board;

})();
