// Generated by CoffeeScript 1.9.3
var Board;

Board = (function() {
  function Board() {
    this.max = 2;
    this.size = {
      cols: 8,
      rows: 8
    };
    this.rows = this.empty_board();
  }

  Board.prototype.empty_board = function() {
    var i, j, k, l, ref, ref1, row, rows;
    rows = [];
    for (i = k = 0, ref = this.size.rows - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
      row = [];
      for (j = l = 0, ref1 = this.size.cols - 1; 0 <= ref1 ? l <= ref1 : l >= ref1; j = 0 <= ref1 ? ++l : --l) {
        row.push(new Piece(this.max, true));
      }
      rows.push(row);
    }
    return rows;
  };

  Board.prototype.add_row = function() {
    var col, i, k, l, piece, ref, ref1, results, row;
    results = [];
    for (col = k = 0, ref = this.size.cols - 1; 0 <= ref ? k <= ref : k >= ref; col = 0 <= ref ? ++k : --k) {
      piece = new Piece(this.max);
      if (!piece.empty && this.rows.length > 0) {
        for (i = l = 1, ref1 = this.rows.length - 1; 1 <= ref1 ? l <= ref1 : l >= ref1; i = 1 <= ref1 ? ++l : --l) {
          row = this.rows.length - i;
          this.rows[row][col] = this.rows[row - 1][col];
        }
        results.push(this.rows[0][col] = piece);
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  return Board;

})();
