// Generated by CoffeeScript 1.9.3
var Piece;

Piece = (function() {
  function Piece(max) {
    this.dragging = false;
    this.value = Math.ceil(Math.random() * max);
  }

  Piece.prototype.drag = function(event) {
    return this.dragging = true;
  };

  Piece.prototype.matches = function(piece) {
    return piece !== this && piece.value === this.value;
  };

  return Piece;

})();
