// Generated by CoffeeScript 1.9.3
var Row;

Row = (function() {
  function Row(cols, max) {
    this.pieces = (function() {
      var i, ref, results;
      results = [];
      for (i = 1, ref = cols; 1 <= ref ? i <= ref : i >= ref; 1 <= ref ? i++ : i--) {
        results.push(new Piece(max));
      }
      return results;
    })();
  }

  return Row;

})();
